[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cs336_basics"
version = "0.1.0"

[tool.setuptools.packages]
find = {}                          # 或者显式写 packages = ["cs336_basics"]